// login
export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// register
export const REGISTER_BEGIN = 'REGISTER_BEGIN';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

// logout
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// modal error
export const MODAL_TOGGLE = 'MODAL_TOGGLE';

// errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// participant contest
export const GET_PARTICIPANT_CONTEST_BEGIN = 'GET_PARTICIPANT_CONTEST_BEGIN';
export const GET_PARTICIPANT_CONTEST_SUCCESS = 'GET_PARTICIPANT_CONTEST_SUCCESS';
export const GET_PARTICIPANT_CONTEST_FAILED = 'GET_PARTICIPANT_CONTEST_FAILED';

// provider contest
export const GET_PROVIDER_CONTEST_BEGIN = 'GET_PROVIDER_CONTEST_BEGIN';
export const GET_PROVIDER_CONTEST_SUCCESS = 'GET_PROVIDER_CONTEST_SUCCESS';
export const GET_PROVIDER_CONTEST_FAILED = 'GET_PROVIDER_CONTEST_FAILED';

// search get all
export const POST_SEARCH_ALL_BEGIN = 'POST_SEARCH_ALL_BEGIN';
export const POST_SEARCH_ALL_SUCCESS = 'POST_SEARCH_ALL_SUCCESS';
export const POST_SEARCH_ALL_FAILED = 'POST_SEARCH_ALL_FAILED';

// search provider
export const POST_SEARCH_PROVIDER_BEGIN = 'POST_SEARCH_PROVIDER_BEGIN';
export const POST_SEARCH_PROVIDER_SUCCESS = 'POST_SEARCH_PROVIDER_SUCCESS';
export const POST_SEARCH_PROVIDER_FAILED = 'POST_SEARCH_PROVIDER_FAILED';

// search participant
export const POST_SEARCH_PARTICIPANT_BEGIN = 'POST_SEARCH_PARTICIPANT_BEGIN';
export const POST_SEARCH_PARTICIPANT_SUCCESS = 'POST_SEARCH_PARTICIPANT_SUCCESS';
export const POST_SEARCH_PARTICIPANT_FAILED = 'POST_SEARCH_PARTICIPANT_FAILED';

// get contest detail
export const GET_CONTEST_DETAIL_BEGIN = 'GET_CONTEST_DETAIL_BEGIN';
export const GET_CONTEST_DETAIL_SUCCESS = 'GET_CONTEST_DETAIL_SUCCESS';
export const GET_CONTEST_DETAIL_FAILED = 'GET_CONTEST_DETAIL_FAILED';

// get submission
export const GET_SUBMISSION_BEGIN = 'GET_SUBMISSION_BEGIN';
export const GET_SUBMISSION_SUCCESS = 'GET_SUBMISSION_SUCCESS';
export const GET_SUBMISSION_FAILED = 'GET_SUBMISSION_FAILED';

// post submission
export const POST_SUBMISSION_BEGIN = 'POST_SUBMISSION_BEGIN';
export const POST_SUBMISSION_SUCCESS = 'POST_SUBMISSION_SUCCESS';
export const POST_SUBMISSION_FAILED = 'POST_SUBMISSION_FAILED';

// update close contest
export const GET_UPDATE_CLOSE_BEGIN = 'GET_UPDATE_CLOSE_BEGIN';
export const GET_UPDATE_CLOSE_SUCCESS = 'GET_UPDATE_CLOSE_SUCCESS';
export const GET_UPDATE_CLOSE_FAILED = 'GET_UPDATE_CLOSE_FAILED';

// update winner contest
export const GET_UPDATE_WINNER_BEGIN = 'GET_UPDATE_WINNER_BEGIN';
export const GET_UPDATE_WINNER_SUCCESS = 'GET_UPDATE_WINNER_SUCCESS';
export const GET_UPDATE_WINNER_FAILED = 'GET_UPDATE_WINNER_FAILED';

// get contest winner
export const GET_WINNER_BEGIN = 'GET_WINNER_BEGIN';
export const GET_WINNER_SUCCESS = 'GET_WINNER_SUCCESS';
export const GET_WINNER_FAILED = 'GET_WINNER_FAILED';

// get admin dashboard
export const GET_ADMIN_DASHBOARD_BEGIN = 'GET_ADMIN_DASHBOARD_BEGIN';
export const GET_ADMIN_DASHBOARD_SUCCESS = 'GET_ADMIN_DASHBOARD_SUCCESS';
export const GET_ADMIN_DASHBOARD_FAILED = 'GET_ADMIN_DASHBOARD_FAILED';

// get admin dashboard paid
export const GET_ADMIN_DASHBOARD_PAID_BEGIN = 'GET_ADMIN_DASHBOARD_PAID_BEGIN';
export const GET_ADMIN_DASHBOARD_PAID_SUCCESS = 'GET_ADMIN_DASHBOARD_PAID_SUCCESS';
export const GET_ADMIN_DASHBOARD_PAID_FAILED = 'GET_ADMIN_DASHBOARD_PAID_FAILED';

// get admin dashboard unpaid
export const GET_ADMIN_DASHBOARD_UNPAID_BEGIN = 'GET_ADMIN_DASHBOARD_UNPAID_BEGIN';
export const GET_ADMIN_DASHBOARD_UNPAID_SUCCESS = 'GET_ADMIN_DASHBOARD_UNPAID_SUCCESS';
export const GET_ADMIN_DASHBOARD_UNPAID_FAILED = 'GET_ADMIN_DASHBOARD_UNPAID_FAILED';

// post provider payment
export const POST_PROVIDER_PAYMENT_BEGIN = 'POST_PROVIDER_PAYMENT_BEGIN';
export const POST_PROVIDER_PAYMENT_SUCCESS = 'POST_PROVIDER_PAYMENT_SUCCESS';
export const POST_PROVIDER_PAYMENT_FAILED = 'POST_PROVIDER_PAYMENT_FAILED';

// get provider payment
export const GET_PROVIDER_PAYMENT_BEGIN = 'GET_PROVIDER_PAYMENT_BEGIN';
export const GET_PROVIDER_PAYMENT_SUCCESS = 'GET_PROVIDER_PAYMENT_SUCCESS';
export const GET_PROVIDER_PAYMENT_FAILED = 'GET_PROVIDER_PAYMENT_FAILED';

// get payment status
export const GET_PAYMENT_STATUS_BEGIN = 'GET_PAYMENT_STATUS_BEGIN';
export const GET_PAYMENT_STATUS_SUCCESS = 'GET_PAYMENT_STATUS_SUCCESS';
export const GET_PAYMENT_STATUS_FAILED = 'GET_PAYMENT_STATUS_FAILED';