export const GET_PROFILE_BEGIN = "GET_PROFILE_BEGIN"
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCESS"
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL"

//patch profile

export const PATCH_PROFILE_BEGIN = "PATCH_PROFILE_BEGIN"
export const PATCH_PROFILE_SUCCESS = "PATCH_PROFILE_SUCESS"
export const PATCH_PROFILE_FAIL = "PATCH_PROFILE_FAIL"
